name: mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  location: ^5.0.3
  logger: ^2.2.0
  rxdart: ^0.27.7
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
