name: mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  mqtt_client: ^9.8.1
  rxdart: ^0.27.7
  sensors_plus: ^4.0.2
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  freezed: ^2.4.1

flutter:
  uses-material-design: true
